name: Java CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build with Maven
        run: mvn clean install -P jacoco

      - name: Analyze with SonarCloud
        env:
          ORGANIZATION: ali1416
          PROJECT_KEY: ALI1416_phone2region
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=$ORGANIZATION -Dsonar.projectKey=$PROJECT_KEY -Dsonar.login=$SONAR_TOKEN

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: target/  # 请根据实际情况修改此路径，确保包含所有需要的构建产物
